### ISSUE TITLE
lazy loading routes

### ISSUE THREAD

**Issue by SherOnDale** [zeroDevs/dev-resources-backend#60]
there are a couple of handler functions for lazy loading. but there are no routes for now

**Comment by Oghenebrume50** [comment]
I do not understand this properly, are you referring to lazy loading images? If yes, we could load all images with a placeholder image and only load the actual image when the resource is in view, similar to what is done on medium.com. Why would a route be needed for this.

**Comment by MattCSmith** [comment]
@Oghenebrume50 The point here is to only load exactly what the user will initially view. 
By this I mean the user does not need all 400 resources as the page is loading. Instead we can load say 20, until the user starts to scrolls and then load the next 20. 

This is actually this months coding challenge as well so it will be interesting to see what other people come up with

**Comment by Oghenebrume50** [comment]
okay, I get it now
