### ISSUE TITLE
rename route files

### ISSUE THREAD

**Issue by SherOnDale** [zeroDevs/dev-resources-backend#7]
Could we rename routes files to [filename].route.js just to follow the same convention? BTW why is there is a route for user? Are we gonna let users sign in and register?

**Comment by MattCSmith** [comment]
Yeah the user should be able to authenticate with `passport-discord` and depending upon access, the following should be available:

- Bookmark/Favourite Resources
- Edit/delete resources

**Comment by MattCSmith** [comment]
I agree I think it would nice to have that naming convention.
I was also thinking that perhaps moving some of the files/directories:
- Put `models` in `db`, so everything db related is in db
- Put `app.js` in `routes`, again so everything route related is in routes. Maybe rename `app.js` to something more descriptive.

What do you think?

**Comment by thisisabdus** [comment]
No issue in renaming. Also, if you want to change routes to something more meaningful and self-descriptive. feel free to do that. 
Matt, `app.js` isn't a route file I believe. It contains all express configurations. For example, `body-parser` middlewares, view and static directory config etc.

**Comment by MattCSmith** [comment]
The routes are fine in my opinion. 
I was concerned that have a bot.js and app.js in the same dir could be confusing. App.js is usually the main file, where in this case bot.js is. Maybe express.js would be a better name?
